on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Build
        run: bun run build
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
